In [31]:
import numpy as np

sensor_data = np.array([
    [12, 15, 14, 10, 13],
    [20, 22, 19, 18, 21],
    [30, 28, 27, 29, 31],
    [25, 24, 26, 23, 22]
])
Average = np.mean(sensor_data, axis=1)
print("Average per row:\n", Average )

Maximum = np.max(sensor_data, axis=0)
print("Maximun per column:\n", Maximum)

Normalized = sensor_data / Maximum
print("Normalized Values\n", Normalized)

for i in range(len(Average)):
  if Average[i] > 20:
    print("Machines", i+1)

Reshaped = sensor_data.reshape(2,10)
print("Reshaped Matrix:\n", Reshaped)


Average per row:
 [12.8 20.  29.  24. ]
Maximun per column:
 [30 28 27 29 31]
Normalized Values
 [[0.4        0.53571429 0.51851852 0.34482759 0.41935484]
 [0.66666667 0.78571429 0.7037037  0.62068966 0.67741935]
 [1.         1.         1.         1.         1.        ]
 [0.83333333 0.85714286 0.96296296 0.79310345 0.70967742]]
Machines 3
Machines 4
[[30 28 27 29 31]
 [25 24 26 23 22]]
Reshaped Matrix:
 [[12 15 14 10 13 20 22 19 18 21]
 [30 28 27 29 31 25 24 26 23 22]]


In [43]:
import numpy as np

I = np.random.randint(1, 50, size=(3,3))
H = np.random.randint(1, 50, size=(3,3))
print("Matrix A:\n", I)
print("\nMatrix B:\n" , H)
M = I @ H
print("\nMultiplication of Matrices:\n" , M)
E = I * H
print("\nElement-wise Multiplication:\n", E)
greater_than_100 = M[M > 100]
print("\nElements greater than 100:\n", greater_than_100)
I[I < 10] = 0
H[H < 10] = 0
print("\nMatrix A after replacing <10 with 0:\n", I)
print("\nMatrix B after replacing <10 with 0:\n", H)
stacked = np.vstack((I, H))
print("\nVertically Stacked Matrix:\n", stacked)

Matrix A:
 [[27  8 45]
 [31 43 27]
 [47  6 30]]

Matrix B:
 [[46 37 13]
 [40 49 18]
 [12  7 17]]

Multiplication of Matrices:
 [[2102 1706 1260]
 [3470 3443 1636]
 [2762 2243 1229]]

Element-wise Multiplication:
 [[1242  296  585]
 [1240 2107  486]
 [ 564   42  510]]

Elements greater than 100:
 [2102 1706 1260 3470 3443 1636 2762 2243 1229]

Matrix A after replacing <10 with 0:
 [[27  0 45]
 [31 43 27]
 [47  0 30]]

Matrix B after replacing <10 with 0:
 [[46 37 13]
 [40 49 18]
 [12  0 17]]

Vertically Stacked Matrix:
 [[27  0 45]
 [31 43 27]
 [47  0 30]
 [46 37 13]
 [40 49 18]
 [12  0 17]]


_